# workflow
name: CI
# event that triggers the workflow
# on push branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:



    #tests
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: install dependencies
          run: yarn
        - name: run tests
          run: yarn test

    #build
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - run: npm run build


