# workflow
name: CI
# event that triggers the workflow
# on push branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

    #tests
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: install dependencies
          run: npm install
        - name: run tests
          run: npm run test

    #build
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: install dependencies
          run: npm install
        - name: build app
          run: npm run build

    # build docker image
    build-docker:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build docker image
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sysinfo-api:${{ github.sha }} .
        - name: push docker image
          run: docker push ${{ secrets.DOCKER_USERNAME }}/sysinfo-api:${{ github.sha }}
        - name: tag docker image
          run: docker tag ${{ secrets.DOCKER_USERNAME }}/sysinfo-api:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-app:latest



